services:
  - type: web
    name: lavalust-products
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL_CA
        value: /etc/secrets/aiven-ca.pem
      - key: DB_SSL_CA_CONTENT
        sync: false
      - key: DB_SSL_VERIFY_SERVER_CERT
        value: "true"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false